### PR TITLE
Using maven-dependency-plugin version from parent since MDEP-753 fixed

### PR DESCRIPTION
**Pull request by ao-apps**
Now using maven-dependency-plugin version 3.3.0 from parent, which fixes https://issues.apache.org/jira/browse/MDEP-753

This conflicts with PR #366 and makes #366 unnecessary.

The majority of the edits are related to the new versions inherited from parent-2.16.0

I added any keys referenced in this change to `src/it/resources/local-repo/pgpkeys-cache`, which I assume helps the tests work offline or when keyservers are down.

### CODE REVIEW

**Comment by ao-apps** [comment]
@slawekjaranowski It looks like you have a corrupted cache in this build:

`2022-03-15T23:09:17.2351230Z [main] WARN org.simplify4u.plugins.keyserver.PGPKeysCache - Read cache file: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cache-path-test13955116150498955684/00/00/0000001234567890.asc.404
2022-03-15T23:09:17.2352260Z java.lang.NumberFormatException: For input string: ""
2022-03-15T23:09:17.2353020Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
2022-03-15T23:09:17.2353750Z 	at java.base/java.lang.Long.parseLong(Long.java:721)
2022-03-15T23:09:17.2354370Z 	at java.base/java.lang.Long.parseLong(Long.java:836)
2022-03-15T23:09:17.2355130Z 	at org.simplify4u.plugins.keyserver.PGPKeysCache.lambda$checkNotFoundCache$969792f5$1(PGPKeysCache.java:207)`

**Comment by ao-apps** [comment]
@slawekjaranowski Only one transient build failure remains, which is the same issue affecting the other builds.  I hope this will meet your standards.

Thank you,
- Dan

**Comment by ao-apps** [comment]
Rebased onto PR #369

**Comment by ao-apps** [comment]
@slawekjaranowski rebased and ready-to-go

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
